# -*- coding: utf-8 -*-
"""PruebaColab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102pIrbw5Fk6vq5evugibF4FiDhZNvj-i
"""

nombre = "Jorge"
edad = 24

print(nombre)

nombre = "Pedro"

"""**Lo que sigue es una funcion**"""

def mostrar_nombre(persona):
  print('Hola '+persona)

mostrar_nombre('Milena')